# buildspec.yml
version: 0.2

phases:
  install:
      runtime-versions: ruby: 2.6.5
  build:
    commands:
      - echo Build started on `date`
  post_build:
    commands:
      - echo Build completed on `date`
post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - target/psql_test.jar
